### ISSUE TITLE
BJSWA service area seems wrong

### ISSUE THREAD

**Issue by ksonda** [cgs-earth/ref_pws#10]
@aashnasawhney @wgrimshaw 

I am removing the recently submitted boundary for PWSID SC0720003

I approved before checking in detail. It seems wrong, this is the boundary  submitted:
![image](https://user-images.githubusercontent.com/44071350/182621767-c668c652-cc1f-4dea-8b7d-ec46446dfbd2.png)

and here is the image from the BJSWA CCR
![image](https://user-images.githubusercontent.com/44071350/182621922-91b162e4-4cf6-4875-9e81-25fcc2cf719b.png)

Can you clarify?

**Comment by aashnasawhney** [comment]
My apologies, I uploaded this previously digitized boundary which I compared to an uploaded map in our files that I now see is not the same map on their website. I will correct that!
